### ISSUE TITLE
Not compatible with vscode 1.72

### ISSUE THREAD

**Issue by lohnsonok** [rubberduck-ai/rubberduck-vscode#1]
I can't install on my vscode

**Comment by lgrammel** [comment]
Thanks for letting me know! 

I've changed the minimal required VSCode version to 1.72. Check out Rubberduck v0.0.8 - you should be able to install it.

Please re-open if you still run into this issue.

**Comment by lgrammel** [comment]
https://github.com/all-contributors please add @lohnsonok for bug report

**Comment by lgrammel** [comment]
@all-contributors please add @lohnsonok for bug report
