### ISSUE TITLE
Support for OpenAI's new GPT-4-1106-preview model, also known as GPT-4 Turbo with 128K context window.

### ISSUE THREAD

**Issue by danielbowne** [rubberduck-ai/rubberduck-vscode#106]
## Is this request related to a problem? Please describe.

I have been utilizing the 'Rubberduck: ChatGPT for Visual Studio Code' tool extensively in my work, leveraging its integration with OpenAI's GPT models for enhanced functionality. However, with the recent announcement of OpenAI's new GPT-4-1106-preview model, also known as GPT-4 Turbo, which offers an expanded 128K context window and lower operational costs. The absence of this model in 'Rubberduck: ChatGPT for Visual Studio Code' limits our ability to leverage the extended context for more complex queries and benefit from the cost efficiency that this new model promises.

## Describe the solution you'd like

I propose that the 'Rubberduck: ChatGPT for Visual Studio Code' tool be updated to integrate the GPT-4-1106-preview model. This integration should include:

- Adaptation to the 128K context window: Ensuring that 'Rubberduck: ChatGPT for Visual Studio Code' can effectively utilize the extended context limit for more comprehensive and detailed interactions.
- Cost Optimization: Leveraging the lower cost of the GPT-4-1106-preview to make 'Rubberduck: ChatGPT for Visual Studio Code' more economical for users, particularly those who use the tool extensively.
- Maintaining Compatibility: Ensuring that the tool remains compatible with previous GPT models for users who prefer or require them.
- This update would significantly enhance 'Rubberduck: ChatGPT for Visual Studio Codes capabilities, allowing users to engage in more complex and extended dialogues with the AI, and reduce operational costs.

## Additional context

As of now, there is no additional context or comparative tools to showcase. However, the integration of this model aligns with the forward-looking approach of keeping 'Rubberduck: ChatGPT for Visual Studio Code' at the forefront of AI-assisted tools. The extended context and cost-efficiency of GPT-4-1106-preview model are crucial for developers and professionals who rely on cutting-edge technology to streamline their workflows and optimize costs.

**Comment by restlessronin** [comment]
I notice that this support already seems to be in the `modelfusion` dependency, although the API has changed somewhat. This would be an important supporting feature for [this PR](https://github.com/rubberduck-ai/rubberduck-vscode/pull/108)

**Comment by lgrammel** [comment]
@restlessronin yup, would be awesome to upgrade it. The changes to the modelfusion api should be minor. I also wanted to add ollama support at some point.

**Comment by lgrammel** [comment]
@restlessronin I've upgraded modelfusion to the latest version, so adding gpt-4-1106 support should be easy now
