### ISSUE TITLE
Show "Enter OpenAI API Key" button instead of start chat in the side panel when no API key has been entered yet

### ISSUE THREAD

**Issue by lgrammel** [rubberduck-ai/rubberduck-vscode#16]
## Is this request related to a problem? Please describe.

This should make onboarding smoother.

## Describe the solution you'd like

Show "Enter OpenAI API Key" button instead of start chat in the side panel when no API key has been entered yet.

**Comment by nicoespeon** [comment]
https://user-images.githubusercontent.com/1094774/218515181-5f868da5-6fbb-49c2-b398-cb390ba4846b.mp4

There you go. It listens to the API key updates and renders a button instead of the chat otherwise.
