### ISSUE TITLE
Add settings to hide chat actions from the context menu

### ISSUE THREAD

**Issue by lgrammel** [rubberduck-ai/rubberduck-vscode#18]
This should be configurable per action. The key could e.g. be

`rubberduck.action.ACTION_NAME.showInEditorContextMenu` (boolean, default true)

Steps:
* add configurable key (package.json)
* add to context menu item when clauses (package.json)
* define settings ui (package.json)
* document (extension README)

**Comment by mshepanski-nasuni** [comment]
Also agree, the context menu options feel like spam to me in an otherwise great extension.
