### ISSUE TITLE
Add Rubberduck to Open VSX

### ISSUE THREAD

**Issue by sbstn87** [rubberduck-ai/rubberduck-vscode#3]
Hi,

can you add Rubberduck to https://open-vsx.org/?

It will make it possible to use it in non-Microsoft builds of VS Code.

**Comment by nicoespeon** [comment]
Good point @sbstn87, I'll make that happen 👍

**Comment by nicoespeon** [comment]
There you go!

https://open-vsx.org/extension/rubberduck/rubberduck-vscode

Thanks for suggesting @sbstn87

**Comment by lgrammel** [comment]
@all-contributors @sbstn87 for idea

**Comment by lgrammel** [comment]
https://github.com/all-contributors @sbstn87 for ideas

**Comment by lgrammel** [comment]
@all-contributors add sbstn87 for ideas
