### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'message')

### ISSUE THREAD

**Issue by RatoGBM** [rubberduck-ai/rubberduck-vscode#32]
<img width="486" alt="Screenshot 2023-02-11 at 22 40 41" src="https://user-images.githubusercontent.com/80184495/218291773-0923b1cf-0cb7-4f87-ae67-7b40d582fe51.png">
I entered my API key, but it doesn't work.

Sorry if I sound like a total newbie (which I am), but I really have no expertise in solving this kind of problems, so pls help.

Thanks.

**Comment by lgrammel** [comment]
Thanks for reporting the bug! I'll take a look.

**Comment by lgrammel** [comment]
v1.8.4 should show the full error message from OpenAI now. I suspect there is something wrong with the API key that you entered (maybe it's out of quota, or there was a typo and it's invalid).

**Comment by lgrammel** [comment]
@all-contributors please add @RatoGBM for bug report

**Comment by RatoGBM** [comment]
Yes it displayed the whole error message, it was out of quota. Thank you
