### ISSUE TITLE
Start Chat hotkey is the same as Redo hotkey on Windows. 

### ISSUE THREAD

**Issue by MercerK** [rubberduck-ai/rubberduck-vscode#37]
## Describe the bug

The Start Chat hotkey is the same as Redo Hotkey on Windows. (Ctrl - Y)

## How to reproduce

Ctrl Y opens up Start Chat, versus Redo.

## Expected behavior

The extension should not be setting hotkeys similar to standard hotkeys. 

Recommend using a different hotkey for Start Chat. 

## Screenshots

![image](https://user-images.githubusercontent.com/13123338/218344825-af72fb7a-df11-4530-b353-6fa4a6113752.png)

![image](https://user-images.githubusercontent.com/13123338/218344811-6fe9f05b-aa30-46c5-a037-94b2773b4e66.png)

**Comment by lgrammel** [comment]
@all-contributors add @MercerK for bug
