### ISSUE TITLE
Add proxy configuration for OpenAI URL

### ISSUE THREAD

**Issue by lgrammel** [rubberduck-ai/rubberduck-vscode#39]
Add a configurable base URL that is used instead of the OpenAI URL in requests.

**Comment by dzcpy** [comment]
Really need this, hope it can be supported in the future 🙏

**Comment by lgrammel** [comment]
@dzcpy not forgotten about it, just super busy. Would you by any chance be able to send a pull request?

**Comment by dzcpy** [comment]
> @dzcpy not forgotten about it, just super busy. Would you by any chance be able to send a pull request?

Thanks for your reply. Sure, I'll try, but I'm a bit busy these a few days, not sure when I can get it done
