### ISSUE TITLE
Option to disable italic font style in question

### ISSUE THREAD

**Issue by tennox** [rubberduck-ai/rubberduck-vscode#55]
Thanks for this rather amazing extension! :heart: :rocket: 

## Is this request related to a problem? Please describe.

I find the italic style of the font in the question a bit hard to read (and especially edit - seeing where the cursor is), and would like to disable it:
![image](https://user-images.githubusercontent.com/2084639/221596831-b04321f7-622f-4906-9987-bfb2d0f9892e.png)

## Describe the solution you'd like

As I guess it's a question of taste, a config option would be nice.

**Comment by lgrammel** [comment]
@all-contributors add @tennox for ideas

**Comment by lgrammel** [comment]
I agree, good catch. Italics were an artifact from an earlier version and are not needed any more, because the background color is different for user messages. I've removed italics in 1.12.1 to make the UI more legible.
