### ISSUE TITLE
Exceeded your current quota

### ISSUE THREAD

**Issue by AlexMyddleware** [rubberduck-ai/rubberduck-vscode#59]
## Describe the bug

I have a chatgpt plus account and I correctly generated an API Key and fed it to Rubberduck. Once I try to initiate a chat I get the following error message:

"Error: You exceeded your current quota, please check your plan and billing details."

At first I expected this to be an openAI issue, but I went to chatgpt and it works just fine, there is no error message.

## How to reproduce

Install the extension and use your API key, no other steps were taken. This was not solved by disabling-reenabling the extension, nor by uninstalling-reinstalling it.

## Expected behavior

no error message, response from the extension

## Screenshots

https://imgur.com/iLbg78X

## Additional information

- Version of the extension impacted: v1.12.1 for vscode 1.76.0

_🧙‍ Add any other context about the problem here._

**Comment by lgrammel** [comment]
It means that you used up your free OpenAI credits. The extension does not come with a plan. You are using your own OpenAI account and subscription. You can see you OpenAI usage here: https://platform.openai.com/account/usage

I'm not sure how OpenAI handles chatgpt plus accounts, but it might be separate from api credits.

**Comment by AlexMyddleware** [comment]
@lgrammel, thanks for your reply. I checked my account and you are right, I don't have any credit, this seems to be indeed separated from the chatGPT plus plan. You may close the issue.
