### ISSUE TITLE
Add syntax highlight for language "twig"

### ISSUE THREAD

**Issue by alessandro-newzoo** [rubberduck-ai/rubberduck-vscode#60]
Not much to add, besides thanking you so much for this fantastic extension!

**Useful links:**
- The extension I use for syntax highlighting, which I believe is the one that works best: https://github.com/mblode/vscode-twig-language-2
- Twig documentation: https://twig.symfony.com/doc/

**Comment by lgrammel** [comment]
We are using Prism for syntax highlighting (see https://github.com/rubberduck-ai/rubberduck-vscode/blob/main/lib/webview/src/component/DiffView.tsx#L219 ). Can you check if it provides support for twig?

**Comment by nicoespeon** [comment]
![twig](https://user-images.githubusercontent.com/1094774/223141613-d70f3a02-1d0c-49fb-a3a4-fabf729252dd.png)

There you go! It will be available with the next release. 
Thanks for suggesting!

@all-contributors please add alessandro-newzoo for ideas

**Comment by alessandro-newzoo** [comment]
> ![twig](https://user-images.githubusercontent.com/1094774/223141613-d70f3a02-1d0c-49fb-a3a4-fabf729252dd.png)
> 
> There you go! It will be available with the next release. Thanks for suggesting!
> 
> @all-contributors please add alessandro-newzoo for ideas

legend! thanks a lot!
