### ISSUE TITLE
Add syntax highlight for language "django-html"

### ISSUE THREAD

**Issue by Void-n-Null** [rubberduck-ai/rubberduck-vscode#62]
## Is this request related to a problem? Please describe.

_A clear and concise description of what the problem is (e.g. "I'm always frustrated when […]")._

## Describe the solution you'd like

_A clear and concise description of what you want to happen._

## Additional context

_Add any other information or screenshots about the feature request here (e.g. a gif showing how another tool does it)._

**Comment by Void-n-Null** [comment]
The extension asked me to post an issue, I'm not gonna bother filling it in, but i will post it. Lol

**Comment by nicoespeon** [comment]
Well, thank you for opening the issue. That made us aware of the `django-html` and `django-txt` languages that are contributed by https://marketplace.visualstudio.com/items?itemName=batisteo.vscode-django

I added support for these, which will be part of the next release.

https://github.com/all-contributors please add Void-n-Null for ideas

**Comment by nicoespeon** [comment]
@all-contributors please add Void-n-Null for ideas
