### ISSUE TITLE
Add syntax highlight for language "java"

### ISSUE THREAD

**Issue by AlexeyLavrentev** [rubberduck-ai/rubberduck-vscode#68]
## Is this request related to a problem? Please describe.

_A clear and concise description of what the problem is (e.g. "I'm always frustrated when […]")._

## Describe the solution you'd like

_A clear and concise description of what you want to happen._

## Additional context

_Add any other information or screenshots about the feature request here (e.g. a gif showing how another tool does it)._

**Comment by lgrammel** [comment]
Available in v1.15

**Comment by lgrammel** [comment]
@all-contributors add AlexeyLavrentev for ideas
