### ISSUE TITLE
Add syntax highlight for language "powershell"

### ISSUE THREAD

**Issue by WittyDingo** [rubberduck-ai/rubberduck-vscode#72]
## Is this request related to a problem? Please describe.

Unable to highlight syntax for language powershell.
We could not find a matching Prism grammar for language powershell. We used the default one (text).

## Describe the solution you'd like

_A clear and concise description of what you want to happen._

## Additional context

_Add any other information or screenshots about the feature request here (e.g. a gif showing how another tool does it)._

**Comment by lgrammel** [comment]
Available in v1.15

**Comment by lgrammel** [comment]
@all-contributors add WittyDingo for ideas
