### ISSUE TITLE
Embedded code font size may look weird

### ISSUE THREAD

**Issue by nicoespeon** [rubberduck-ai/rubberduck-vscode#8]
![code font size](https://user-images.githubusercontent.com/1094774/216643249-b68d2d67-b9ae-4d4d-bdea-a0d8e3023c63.png)

It looks like the code parts are not using the same font size as the rest. In this example, it seems to come from the theme/local config, but the rest of the text isn't.

**Comment by lgrammel** [comment]
@all-contributors add @nicoespeon for bug
