### ISSUE TITLE
Doesn't use any local file context?

### ISSUE THREAD

**Issue by alexkreidler** [rubberduck-ai/rubberduck-vscode#98]
## Describe the bug
I asked it to "Add a bench command to this CLI", but it returned code using `argparse` not `typer` which the current file I'm editing was using.

## How to reproduce
Ask a question that needs knowledge from the open file

## Expected behavior
It should use the open file or more files in the repo as context to answer the question/generate code.

## Additional information

- Version of the extension impacted: 1.15.0

**Comment by lgrammel** [comment]
You can control the context that you pass into rubberduck by selecting the text.
